#!/usr/bin/env bash
# =============================================================================
# generate-report.sh
# CM runs this on BUILD DAY after finalising manifest.yml.
#
# What it does:
#   1. Reads releases/SPRINT/manifest.yml
#   2. Fetches the HEAD commit SHA for each included team's sprint branch
#      (if not already filled in manifest.yml)
#   3. Generates releases/SPRINT/RELEASE-NOTES.md
#
# Usage:
#   ./scripts/generate-report.sh sprint-12
#   ./scripts/generate-report.sh sprint-12-patch1
# =============================================================================

set -euo pipefail

SPRINT=${1:-}
if [[ -z "$SPRINT" ]]; then
  echo "Usage: $0 <sprint-name>   e.g. $0 sprint-12"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST_ROOT="$(dirname "$SCRIPT_DIR")"
MANIFEST="$MANIFEST_ROOT/releases/$SPRINT/manifest.yml"
OUTPUT="$MANIFEST_ROOT/releases/$SPRINT/RELEASE-NOTES.md"

if [[ ! -f "$MANIFEST" ]]; then
  echo "Error: $MANIFEST not found"
  exit 1
fi

# ── Minimal YAML parser helpers ───────────────────────────────────────────────
# Reads a top-level key value (no nesting)
yaml_get() { grep -m1 "^$1:" "$MANIFEST" | sed 's/^[^:]*: *//' | tr -d '"'; }

# Reads a value nested under a team block: yaml_team_get conversion included
yaml_team_get() {
  local team="$1" key="$2"
  awk "/^  $team:/{found=1} found && /^    $key:/{print; found=0}" "$MANIFEST" \
    | sed 's/^[^:]*: *//' | tr -d '"'
}

# Reads a list field under a team block into a comma-separated string
yaml_team_list() {
  local team="$1" key="$2"
  awk "/^  $team:/{found=1} found && /^    $key:/{p=1; next} p && /^ *- /{print; next} p && /^    [^ ]/{p=0}" "$MANIFEST" \
    | sed 's/ *- *//' | tr '\n' ',' | sed 's/,$//'
}

BUILD_DATE=$(yaml_get "build_date")
BUILT_BY=$(yaml_get "built_by")
ELM_URL=$(yaml_get "elm_sprint_url")
SPRINT_DATES=$(yaml_get "sprint_dates")

TEAMS=("conversion" "interfaces" "workflow_config" "func_config")
TEAM_LABELS=("Conversion" "Interfaces" "Workflow Config" "Functional Product Config")

COTS_PRODUCT=$(yaml_team_get "cots" "product")
COTS_VERSION=$(yaml_team_get "cots" "version")
COTS_PREV=$(yaml_team_get "cots" "previous_version")
COTS_INCLUDED=$(yaml_team_get "cots" "included")
COTS_NOTES=$(yaml_team_get "cots" "notes")

SIT_STATUS=$(yaml_team_get "sit" "status")
UAT_STATUS=$(yaml_team_get "uat" "status")

# ── Write report ──────────────────────────────────────────────────────────────
cat > "$OUTPUT" <<HEADER
# Release Notes — $SPRINT

| | |
|---|---|
| Sprint dates | $SPRINT_DATES |
| Build date | ${BUILD_DATE:-TBD} |
| Built by | ${BUILT_BY:-TBD} |
| ELM Sprint | $ELM_URL |

---

## Teams Included in This Build

HEADER

for i in "${!TEAMS[@]}"; do
  TEAM="${TEAMS[$i]}"
  LABEL="${TEAM_LABELS[$i]}"
  INCLUDED=$(yaml_team_get "$TEAM" "included")
  COMMIT=$(yaml_team_get "$TEAM" "commit")
  BRANCH=$(yaml_team_get "$TEAM" "branch")
  SUMMARY=$(yaml_team_get "$TEAM" "summary")
  ITEMS=$(yaml_team_list "$TEAM" "elm_work_items")

  if [[ "$INCLUDED" == "true" ]]; then
    cat >> "$OUTPUT" <<TEAM_BLOCK
### $LABEL ✅
- **Branch:** \`$BRANCH\`
- **Commit:** \`${COMMIT:-not yet recorded}\`
- **ELM items:** ${ITEMS:-none listed}
- **Summary:** ${SUMMARY:-see ELM}

TEAM_BLOCK
  fi
done

cat >> "$OUTPUT" <<DEFERRED
---

## Teams Deferred (not in this build)

DEFERRED

DEFERRED_ANY=false
for i in "${!TEAMS[@]}"; do
  TEAM="${TEAMS[$i]}"
  LABEL="${TEAM_LABELS[$i]}"
  INCLUDED=$(yaml_team_get "$TEAM" "included")
  REASON=$(yaml_team_get "$TEAM" "reason" 2>/dev/null || echo "")

  if [[ "$INCLUDED" == "false" ]]; then
    DEFERRED_ANY=true
    cat >> "$OUTPUT" <<DEFER_BLOCK
### $LABEL ⏸
- **Reason:** ${REASON:-not specified}
- Work deferred to next sprint.

DEFER_BLOCK
  fi
done

if [[ "$DEFERRED_ANY" == "false" ]]; then
  echo "_All teams included in this build._" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
fi

cat >> "$OUTPUT" <<COTS_SECTION
---

## COTS Product

| | |
|---|---|
| Product | $COTS_PRODUCT |
| Version | $COTS_VERSION |
| Previous version | $COTS_PREV |
| Included | $COTS_INCLUDED |

${COTS_NOTES:+> $COTS_NOTES}

See \`cots-$SPRINT.md\` for full hotfix list and impact assessment.

---

## Environment Status

| Environment | Status |
|-------------|--------|
| SIT | $SIT_STATUS |
| UAT | $UAT_STATUS |

---
_Generated by generate-report.sh on $(date "+%Y-%m-%d %H:%M")_
COTS_SECTION

echo "Report written to: $OUTPUT"
echo ""
echo "=== Next steps: ==="
echo "  1. Review $OUTPUT"
echo "  2. git add releases/$SPRINT/ && git commit -m 'Release: $SPRINT build report'"
echo "  3. Open PR titled 'Release $SPRINT' for CM team review"
echo "  4. Deploy to SIT, then run: ./scripts/tag-environments.sh $SPRINT sit"
